### ISSUE TITLE
Add cat-* id to crosswalk

### ISSUE THREAD

**Issue by hellkite500** [dblodgett-usgs/hygeo#15]
Consider adding catchment id to the crosswalk file to explicitly link catchments to "reaches" via COMID.

**Comment by dblodgett-usgs** [comment]
I added "realized_catchment" to the waterbody_data.geojson to make this connection. Is that not enough?

**Comment by hellkite500** [comment]
It is, but indirectly.  I guess it depends on what the crosswalk is intended to link.

**Comment by dblodgett-usgs** [comment]
Yeah -- it is indirect. I think the most sustainable thing to do would be to resolve the indirect links in a cached convenience lookup table. 

The trick is that in the future, there will be a collection of waterbodies for a catchment and a simple lookup won't be enough. You'll need to know "flow coming into the catchment goes into the top of that waterbody that is a member of the catchment's set". 

The lookup table is saying which COMID(s) goes with which HY_Catchment. Since some got lumped together, there is a 1:many COMID to HY_Catchment.

What a mess. 

All that said, I can add the cat-* ids if it would be helpful right now and we can tease it apart later. Right now that cross walk is waterbody oriented but there's no reason I wouldn't add the catchment IDs since we are 1:1 catchment to waterbody for the time being.

**Comment by dblodgett-usgs** [comment]
OK -- this is done. The refactor I just did refocuses the work around catchment flowpaths and the cross walk is not between catchments and NHDPlus comids.
